version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - e-shop-network
    expose:
      - 5000
    volumes:
      - ./backend:/app
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - e-shop-network
    expose:
      - 3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

networks:
  e-shop-network:
    driver: bridge
    
volumes:
  frontend:
  backend:

